'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
'
Namespace Timesheet
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TimesheetSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Timesheet
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetUserTimesheetEntriesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTimesheetEntryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSumTimeLoggedTodayOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteTimesheetEntryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AddTimesheetEntryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateTimesheetEntryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTimesheetEntriesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetProjectTimesheetEntriesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private MarkEntryBillableOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WindowsApplication1.My.MySettings.Default.HolidayImp_Timesheet_Timesheet
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetUserTimesheetEntriesCompleted As GetUserTimesheetEntriesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTimesheetEntryCompleted As GetTimesheetEntryCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSumTimeLoggedTodayCompleted As GetSumTimeLoggedTodayCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteTimesheetEntryCompleted As DeleteTimesheetEntryCompletedEventHandler
        
        '''<remarks/>
        Public Event AddTimesheetEntryCompleted As AddTimesheetEntryCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateTimesheetEntryCompleted As UpdateTimesheetEntryCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTimesheetEntriesCompleted As GetTimesheetEntriesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetProjectTimesheetEntriesCompleted As GetProjectTimesheetEntriesCompletedEventHandler
        
        '''<remarks/>
        Public Event MarkEntryBillableCompleted As MarkEntryBillableCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserTimesheetEntries", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserTimesheetEntries(ByVal userId As Integer, ByVal startDate As Date, ByVal endDate As Date) As Timesheet1()
            Dim results() As Object = Me.Invoke("GetUserTimesheetEntries", New Object() {userId, startDate, endDate})
            Return CType(results(0),Timesheet1())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUserTimesheetEntriesAsync(ByVal userId As Integer, ByVal startDate As Date, ByVal endDate As Date)
            Me.GetUserTimesheetEntriesAsync(userId, startDate, endDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUserTimesheetEntriesAsync(ByVal userId As Integer, ByVal startDate As Date, ByVal endDate As Date, ByVal userState As Object)
            If (Me.GetUserTimesheetEntriesOperationCompleted Is Nothing) Then
                Me.GetUserTimesheetEntriesOperationCompleted = AddressOf Me.OnGetUserTimesheetEntriesOperationCompleted
            End If
            Me.InvokeAsync("GetUserTimesheetEntries", New Object() {userId, startDate, endDate}, Me.GetUserTimesheetEntriesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUserTimesheetEntriesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUserTimesheetEntriesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUserTimesheetEntriesCompleted(Me, New GetUserTimesheetEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTimesheetEntry", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTimesheetEntry(ByVal entryId As Integer) As Timesheet1
            Dim results() As Object = Me.Invoke("GetTimesheetEntry", New Object() {entryId})
            Return CType(results(0),Timesheet1)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTimesheetEntryAsync(ByVal entryId As Integer)
            Me.GetTimesheetEntryAsync(entryId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTimesheetEntryAsync(ByVal entryId As Integer, ByVal userState As Object)
            If (Me.GetTimesheetEntryOperationCompleted Is Nothing) Then
                Me.GetTimesheetEntryOperationCompleted = AddressOf Me.OnGetTimesheetEntryOperationCompleted
            End If
            Me.InvokeAsync("GetTimesheetEntry", New Object() {entryId}, Me.GetTimesheetEntryOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTimesheetEntryOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTimesheetEntryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTimesheetEntryCompleted(Me, New GetTimesheetEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSumTimeLoggedToday", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSumTimeLoggedToday() As Decimal
            Dim results() As Object = Me.Invoke("GetSumTimeLoggedToday", New Object(-1) {})
            Return CType(results(0),Decimal)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSumTimeLoggedTodayAsync()
            Me.GetSumTimeLoggedTodayAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSumTimeLoggedTodayAsync(ByVal userState As Object)
            If (Me.GetSumTimeLoggedTodayOperationCompleted Is Nothing) Then
                Me.GetSumTimeLoggedTodayOperationCompleted = AddressOf Me.OnGetSumTimeLoggedTodayOperationCompleted
            End If
            Me.InvokeAsync("GetSumTimeLoggedToday", New Object(-1) {}, Me.GetSumTimeLoggedTodayOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSumTimeLoggedTodayOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSumTimeLoggedTodayCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSumTimeLoggedTodayCompleted(Me, New GetSumTimeLoggedTodayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteTimesheetEntry", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub DeleteTimesheetEntry(ByVal timesheetId As Integer)
            Me.Invoke("DeleteTimesheetEntry", New Object() {timesheetId})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteTimesheetEntryAsync(ByVal timesheetId As Integer)
            Me.DeleteTimesheetEntryAsync(timesheetId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteTimesheetEntryAsync(ByVal timesheetId As Integer, ByVal userState As Object)
            If (Me.DeleteTimesheetEntryOperationCompleted Is Nothing) Then
                Me.DeleteTimesheetEntryOperationCompleted = AddressOf Me.OnDeleteTimesheetEntryOperationCompleted
            End If
            Me.InvokeAsync("DeleteTimesheetEntry", New Object() {timesheetId}, Me.DeleteTimesheetEntryOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteTimesheetEntryOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteTimesheetEntryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteTimesheetEntryCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddTimesheetEntry", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub AddTimesheetEntry(ByVal projectId As Integer, ByVal userId As Integer, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal activityId As System.Nullable(Of Integer), ByVal numberOfHours As Decimal, ByVal timesheetDate As Date, ByVal dateEntered As Date, ByVal description As String, ByVal chargeable As Boolean, ByVal startTime As String, ByVal endTime As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal phaseId As System.Nullable(Of Integer), <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal taskId As System.Nullable(Of Integer))
            Me.Invoke("AddTimesheetEntry", New Object() {projectId, userId, activityId, numberOfHours, timesheetDate, dateEntered, description, chargeable, startTime, endTime, phaseId, taskId})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddTimesheetEntryAsync(ByVal projectId As Integer, ByVal userId As Integer, ByVal activityId As System.Nullable(Of Integer), ByVal numberOfHours As Decimal, ByVal timesheetDate As Date, ByVal dateEntered As Date, ByVal description As String, ByVal chargeable As Boolean, ByVal startTime As String, ByVal endTime As String, ByVal phaseId As System.Nullable(Of Integer), ByVal taskId As System.Nullable(Of Integer))
            Me.AddTimesheetEntryAsync(projectId, userId, activityId, numberOfHours, timesheetDate, dateEntered, description, chargeable, startTime, endTime, phaseId, taskId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddTimesheetEntryAsync(ByVal projectId As Integer, ByVal userId As Integer, ByVal activityId As System.Nullable(Of Integer), ByVal numberOfHours As Decimal, ByVal timesheetDate As Date, ByVal dateEntered As Date, ByVal description As String, ByVal chargeable As Boolean, ByVal startTime As String, ByVal endTime As String, ByVal phaseId As System.Nullable(Of Integer), ByVal taskId As System.Nullable(Of Integer), ByVal userState As Object)
            If (Me.AddTimesheetEntryOperationCompleted Is Nothing) Then
                Me.AddTimesheetEntryOperationCompleted = AddressOf Me.OnAddTimesheetEntryOperationCompleted
            End If
            Me.InvokeAsync("AddTimesheetEntry", New Object() {projectId, userId, activityId, numberOfHours, timesheetDate, dateEntered, description, chargeable, startTime, endTime, phaseId, taskId}, Me.AddTimesheetEntryOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddTimesheetEntryOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddTimesheetEntryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddTimesheetEntryCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateTimesheetEntry", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateTimesheetEntry(ByVal oTimesheetEntry As Timesheet1)
            Me.Invoke("UpdateTimesheetEntry", New Object() {oTimesheetEntry})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateTimesheetEntryAsync(ByVal oTimesheetEntry As Timesheet1)
            Me.UpdateTimesheetEntryAsync(oTimesheetEntry, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateTimesheetEntryAsync(ByVal oTimesheetEntry As Timesheet1, ByVal userState As Object)
            If (Me.UpdateTimesheetEntryOperationCompleted Is Nothing) Then
                Me.UpdateTimesheetEntryOperationCompleted = AddressOf Me.OnUpdateTimesheetEntryOperationCompleted
            End If
            Me.InvokeAsync("UpdateTimesheetEntry", New Object() {oTimesheetEntry}, Me.UpdateTimesheetEntryOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateTimesheetEntryOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateTimesheetEntryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateTimesheetEntryCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTimesheetEntries", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTimesheetEntries(ByVal startDate As Date, ByVal endDate As Date) As Timesheet1()
            Dim results() As Object = Me.Invoke("GetTimesheetEntries", New Object() {startDate, endDate})
            Return CType(results(0),Timesheet1())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTimesheetEntriesAsync(ByVal startDate As Date, ByVal endDate As Date)
            Me.GetTimesheetEntriesAsync(startDate, endDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTimesheetEntriesAsync(ByVal startDate As Date, ByVal endDate As Date, ByVal userState As Object)
            If (Me.GetTimesheetEntriesOperationCompleted Is Nothing) Then
                Me.GetTimesheetEntriesOperationCompleted = AddressOf Me.OnGetTimesheetEntriesOperationCompleted
            End If
            Me.InvokeAsync("GetTimesheetEntries", New Object() {startDate, endDate}, Me.GetTimesheetEntriesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTimesheetEntriesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTimesheetEntriesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTimesheetEntriesCompleted(Me, New GetTimesheetEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProjectTimesheetEntries", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProjectTimesheetEntries(ByVal startDate As Date, ByVal endDate As Date, ByVal projectId As Integer) As Timesheet1()
            Dim results() As Object = Me.Invoke("GetProjectTimesheetEntries", New Object() {startDate, endDate, projectId})
            Return CType(results(0),Timesheet1())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetProjectTimesheetEntriesAsync(ByVal startDate As Date, ByVal endDate As Date, ByVal projectId As Integer)
            Me.GetProjectTimesheetEntriesAsync(startDate, endDate, projectId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetProjectTimesheetEntriesAsync(ByVal startDate As Date, ByVal endDate As Date, ByVal projectId As Integer, ByVal userState As Object)
            If (Me.GetProjectTimesheetEntriesOperationCompleted Is Nothing) Then
                Me.GetProjectTimesheetEntriesOperationCompleted = AddressOf Me.OnGetProjectTimesheetEntriesOperationCompleted
            End If
            Me.InvokeAsync("GetProjectTimesheetEntries", New Object() {startDate, endDate, projectId}, Me.GetProjectTimesheetEntriesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetProjectTimesheetEntriesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetProjectTimesheetEntriesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetProjectTimesheetEntriesCompleted(Me, New GetProjectTimesheetEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MarkEntryBillable", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub MarkEntryBillable(ByVal timesheetId As Integer, ByVal roleId As Integer, ByVal isBillable As Boolean)
            Me.Invoke("MarkEntryBillable", New Object() {timesheetId, roleId, isBillable})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub MarkEntryBillableAsync(ByVal timesheetId As Integer, ByVal roleId As Integer, ByVal isBillable As Boolean)
            Me.MarkEntryBillableAsync(timesheetId, roleId, isBillable, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub MarkEntryBillableAsync(ByVal timesheetId As Integer, ByVal roleId As Integer, ByVal isBillable As Boolean, ByVal userState As Object)
            If (Me.MarkEntryBillableOperationCompleted Is Nothing) Then
                Me.MarkEntryBillableOperationCompleted = AddressOf Me.OnMarkEntryBillableOperationCompleted
            End If
            Me.InvokeAsync("MarkEntryBillable", New Object() {timesheetId, roleId, isBillable}, Me.MarkEntryBillableOperationCompleted, userState)
        End Sub
        
        Private Sub OnMarkEntryBillableOperationCompleted(ByVal arg As Object)
            If (Not (Me.MarkEntryBillableCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent MarkEntryBillableCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="Timesheet", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Timesheet1
        
        Private tIMESHEET_IDField As Integer
        
        Private pROJECT_IDField As Integer
        
        Private pROJECTField As Project
        
        Private uSER_IDField As Integer
        
        Private uSERField As User
        
        Private aCTIVITY_IDField As System.Nullable(Of Integer)
        
        Private aCTIVITYField As Activity
        
        Private pROJECT_PHASE_IDField As System.Nullable(Of Integer)
        
        Private pROJECT_PHASEField As Project_Phase
        
        Private nUMBER_OF_HOURSField As Decimal
        
        Private tIMESHEET_DATEField As Date
        
        Private dATE_ENTEREDField As Date
        
        Private dESCRIPTIONField As String
        
        Private cHARGEABLEField As Boolean
        
        Private sTART_TIMEField As String
        
        Private eND_TIMEField As String
        
        Private tASK_IDField As System.Nullable(Of Integer)
        
        Private tASK_NAMEField As String
        
        Private pROJECT_USER_ROLE_IDField As System.Nullable(Of Integer)
        
        '''<remarks/>
        Public Property TIMESHEET_ID() As Integer
            Get
                Return Me.tIMESHEET_IDField
            End Get
            Set
                Me.tIMESHEET_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PROJECT_ID() As Integer
            Get
                Return Me.pROJECT_IDField
            End Get
            Set
                Me.pROJECT_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PROJECT() As Project
            Get
                Return Me.pROJECTField
            End Get
            Set
                Me.pROJECTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property USER_ID() As Integer
            Get
                Return Me.uSER_IDField
            End Get
            Set
                Me.uSER_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property USER() As User
            Get
                Return Me.uSERField
            End Get
            Set
                Me.uSERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ACTIVITY_ID() As System.Nullable(Of Integer)
            Get
                Return Me.aCTIVITY_IDField
            End Get
            Set
                Me.aCTIVITY_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ACTIVITY() As Activity
            Get
                Return Me.aCTIVITYField
            End Get
            Set
                Me.aCTIVITYField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PROJECT_PHASE_ID() As System.Nullable(Of Integer)
            Get
                Return Me.pROJECT_PHASE_IDField
            End Get
            Set
                Me.pROJECT_PHASE_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PROJECT_PHASE() As Project_Phase
            Get
                Return Me.pROJECT_PHASEField
            End Get
            Set
                Me.pROJECT_PHASEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMBER_OF_HOURS() As Decimal
            Get
                Return Me.nUMBER_OF_HOURSField
            End Get
            Set
                Me.nUMBER_OF_HOURSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TIMESHEET_DATE() As Date
            Get
                Return Me.tIMESHEET_DATEField
            End Get
            Set
                Me.tIMESHEET_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DATE_ENTERED() As Date
            Get
                Return Me.dATE_ENTEREDField
            End Get
            Set
                Me.dATE_ENTEREDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DESCRIPTION() As String
            Get
                Return Me.dESCRIPTIONField
            End Get
            Set
                Me.dESCRIPTIONField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CHARGEABLE() As Boolean
            Get
                Return Me.cHARGEABLEField
            End Get
            Set
                Me.cHARGEABLEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property START_TIME() As String
            Get
                Return Me.sTART_TIMEField
            End Get
            Set
                Me.sTART_TIMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property END_TIME() As String
            Get
                Return Me.eND_TIMEField
            End Get
            Set
                Me.eND_TIMEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TASK_ID() As System.Nullable(Of Integer)
            Get
                Return Me.tASK_IDField
            End Get
            Set
                Me.tASK_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TASK_NAME() As String
            Get
                Return Me.tASK_NAMEField
            End Get
            Set
                Me.tASK_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PROJECT_USER_ROLE_ID() As System.Nullable(Of Integer)
            Get
                Return Me.pROJECT_USER_ROLE_IDField
            End Get
            Set
                Me.pROJECT_USER_ROLE_IDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Project
        
        Private pROJECT_IDField As Integer
        
        Private pROJECT_NUMBERField As Integer
        
        Private pROJECT_NAMEField As String
        
        Private cUSTOMER_CODEField As String
        
        Private cUSTOMER_OBJECTField As Customer
        
        Private pROJECT_DESCRIPTIONField As String
        
        Private sTART_DATEField As Date
        
        Private tARGET_COMPLETION_DATEField As Date
        
        Private aCTUAL_COMPLETION_DATEField As Date
        
        Private aCTIVEField As Boolean
        
        Private outputValueField As String
        
        Private pHASESField() As Project_Phase
        
        '''<remarks/>
        Public Property PROJECT_ID() As Integer
            Get
                Return Me.pROJECT_IDField
            End Get
            Set
                Me.pROJECT_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PROJECT_NUMBER() As Integer
            Get
                Return Me.pROJECT_NUMBERField
            End Get
            Set
                Me.pROJECT_NUMBERField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PROJECT_NAME() As String
            Get
                Return Me.pROJECT_NAMEField
            End Get
            Set
                Me.pROJECT_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CUSTOMER_CODE() As String
            Get
                Return Me.cUSTOMER_CODEField
            End Get
            Set
                Me.cUSTOMER_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CUSTOMER_OBJECT() As Customer
            Get
                Return Me.cUSTOMER_OBJECTField
            End Get
            Set
                Me.cUSTOMER_OBJECTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PROJECT_DESCRIPTION() As String
            Get
                Return Me.pROJECT_DESCRIPTIONField
            End Get
            Set
                Me.pROJECT_DESCRIPTIONField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property START_DATE() As Date
            Get
                Return Me.sTART_DATEField
            End Get
            Set
                Me.sTART_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TARGET_COMPLETION_DATE() As Date
            Get
                Return Me.tARGET_COMPLETION_DATEField
            End Get
            Set
                Me.tARGET_COMPLETION_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ACTUAL_COMPLETION_DATE() As Date
            Get
                Return Me.aCTUAL_COMPLETION_DATEField
            End Get
            Set
                Me.aCTUAL_COMPLETION_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ACTIVE() As Boolean
            Get
                Return Me.aCTIVEField
            End Get
            Set
                Me.aCTIVEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OutputValue() As String
            Get
                Return Me.outputValueField
            End Get
            Set
                Me.outputValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PHASES() As Project_Phase()
            Get
                Return Me.pHASESField
            End Get
            Set
                Me.pHASESField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Customer
        
        Private cUST_CODEField As String
        
        Private cUSTOMER_NAMEField As String
        
        '''<remarks/>
        Public Property CUST_CODE() As String
            Get
                Return Me.cUST_CODEField
            End Get
            Set
                Me.cUST_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CUSTOMER_NAME() As String
            Get
                Return Me.cUSTOMER_NAMEField
            End Get
            Set
                Me.cUSTOMER_NAMEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Activity
        
        Private aCTIVITY_IDField As Integer
        
        Private aCTIVITY_NAMEField As String
        
        Private aCTIVITY_DESCRIPTIONField As String
        
        Private aCTIVITY_ACTIVEField As Boolean
        
        '''<remarks/>
        Public Property ACTIVITY_ID() As Integer
            Get
                Return Me.aCTIVITY_IDField
            End Get
            Set
                Me.aCTIVITY_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ACTIVITY_NAME() As String
            Get
                Return Me.aCTIVITY_NAMEField
            End Get
            Set
                Me.aCTIVITY_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ACTIVITY_DESCRIPTION() As String
            Get
                Return Me.aCTIVITY_DESCRIPTIONField
            End Get
            Set
                Me.aCTIVITY_DESCRIPTIONField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ACTIVITY_ACTIVE() As Boolean
            Get
                Return Me.aCTIVITY_ACTIVEField
            End Get
            Set
                Me.aCTIVITY_ACTIVEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class User
        
        Private uSER_IDField As Integer
        
        Private uSER_NAMEField As String
        
        Private uSER_EMAILField As String
        
        Private sEND_NAG_EMAILField As Boolean
        
        Private iS_ADMINField As Boolean
        
        Private iS_PMOField As Boolean
        
        Private iS_ACTIVEField As Boolean
        
        Private pROJECT_PLAN_NAMEField As String
        
        '''<remarks/>
        Public Property USER_ID() As Integer
            Get
                Return Me.uSER_IDField
            End Get
            Set
                Me.uSER_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property USER_NAME() As String
            Get
                Return Me.uSER_NAMEField
            End Get
            Set
                Me.uSER_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property USER_EMAIL() As String
            Get
                Return Me.uSER_EMAILField
            End Get
            Set
                Me.uSER_EMAILField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SEND_NAG_EMAIL() As Boolean
            Get
                Return Me.sEND_NAG_EMAILField
            End Get
            Set
                Me.sEND_NAG_EMAILField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IS_ADMIN() As Boolean
            Get
                Return Me.iS_ADMINField
            End Get
            Set
                Me.iS_ADMINField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IS_PMO() As Boolean
            Get
                Return Me.iS_PMOField
            End Get
            Set
                Me.iS_PMOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IS_ACTIVE() As Boolean
            Get
                Return Me.iS_ACTIVEField
            End Get
            Set
                Me.iS_ACTIVEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PROJECT_PLAN_NAME() As String
            Get
                Return Me.pROJECT_PLAN_NAMEField
            End Get
            Set
                Me.pROJECT_PLAN_NAMEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Phase
        
        Private pHASE_IDField As Integer
        
        Private pHASE_NAMEField As String
        
        Private pHASE_DESCRIPTIONField As String
        
        '''<remarks/>
        Public Property PHASE_ID() As Integer
            Get
                Return Me.pHASE_IDField
            End Get
            Set
                Me.pHASE_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PHASE_NAME() As String
            Get
                Return Me.pHASE_NAMEField
            End Get
            Set
                Me.pHASE_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PHASE_DESCRIPTION() As String
            Get
                Return Me.pHASE_DESCRIPTIONField
            End Get
            Set
                Me.pHASE_DESCRIPTIONField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Project_Phase
        
        Private pROJECT_PHASE_IDField As Integer
        
        Private pROJECT_IDField As Integer
        
        Private tARGET_HOURS_PPField As Double
        
        Private tARGET_HOURS_LOEField As Double
        
        Private sTART_TARGETField As Date
        
        Private sTART_ACTUALField As System.Nullable(Of Date)
        
        Private eND_TARGETField As Date
        
        Private eND_ACTUALField As System.Nullable(Of Date)
        
        Private pHASE_IDField As Integer
        
        Private pHASEField As Phase
        
        '''<remarks/>
        Public Property PROJECT_PHASE_ID() As Integer
            Get
                Return Me.pROJECT_PHASE_IDField
            End Get
            Set
                Me.pROJECT_PHASE_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PROJECT_ID() As Integer
            Get
                Return Me.pROJECT_IDField
            End Get
            Set
                Me.pROJECT_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TARGET_HOURS_PP() As Double
            Get
                Return Me.tARGET_HOURS_PPField
            End Get
            Set
                Me.tARGET_HOURS_PPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TARGET_HOURS_LOE() As Double
            Get
                Return Me.tARGET_HOURS_LOEField
            End Get
            Set
                Me.tARGET_HOURS_LOEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property START_TARGET() As Date
            Get
                Return Me.sTART_TARGETField
            End Get
            Set
                Me.sTART_TARGETField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property START_ACTUAL() As System.Nullable(Of Date)
            Get
                Return Me.sTART_ACTUALField
            End Get
            Set
                Me.sTART_ACTUALField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property END_TARGET() As Date
            Get
                Return Me.eND_TARGETField
            End Get
            Set
                Me.eND_TARGETField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property END_ACTUAL() As System.Nullable(Of Date)
            Get
                Return Me.eND_ACTUALField
            End Get
            Set
                Me.eND_ACTUALField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PHASE_ID() As Integer
            Get
                Return Me.pHASE_IDField
            End Get
            Set
                Me.pHASE_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PHASE() As Phase
            Get
                Return Me.pHASEField
            End Get
            Set
                Me.pHASEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetUserTimesheetEntriesCompletedEventHandler(ByVal sender As Object, ByVal e As GetUserTimesheetEntriesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUserTimesheetEntriesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Timesheet1()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Timesheet1())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetTimesheetEntryCompletedEventHandler(ByVal sender As Object, ByVal e As GetTimesheetEntryCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTimesheetEntryCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Timesheet1
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Timesheet1)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetSumTimeLoggedTodayCompletedEventHandler(ByVal sender As Object, ByVal e As GetSumTimeLoggedTodayCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSumTimeLoggedTodayCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Decimal
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Decimal)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub DeleteTimesheetEntryCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub AddTimesheetEntryCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub UpdateTimesheetEntryCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetTimesheetEntriesCompletedEventHandler(ByVal sender As Object, ByVal e As GetTimesheetEntriesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTimesheetEntriesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Timesheet1()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Timesheet1())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetProjectTimesheetEntriesCompletedEventHandler(ByVal sender As Object, ByVal e As GetProjectTimesheetEntriesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetProjectTimesheetEntriesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Timesheet1()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Timesheet1())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub MarkEntryBillableCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
